# Generated by Django 2.1 on 2018-11-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest', models.IntegerField()),
                ('highest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kana_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=255)),
                ('business_hours', models.CharField(max_length=255)),
                ('regular_holiday', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Budget')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
    ]
