# Generated by Django 2.1 on 2018-10-19 14:26

from django.db import migrations


def add_prefectures(apps, schema_editor):
    Prefecture = apps.get_model('shops', 'Prefecture')
    for prefecture_name in ['北海道', '青森県', '茨城県']:
        Prefecture(name=prefecture_name).save()


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_prefectures, reverse_code=migrations.RunPython.noop),
    ]
