# Generated by Django 2.1 on 2018-11-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shops_prefecture_data'),
        # reviews_review テーブルが存在することを前提とする
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
              create view shops_shop_with_score as
              select
                s.*,
                r.score
              from shops_shop s
                left outer join (
                  select shop_id, avg(score) score
                  from reviews_review
                  group by shop_id
                ) r on s.id = r.shop_id
            """,
            # ロールバック時に実行される SQL 文
            reverse_sql="drop view shops_shop_with_score")
    ]
